'use client'

import React, {useEffect} from 'react';
import Head from "next/head";
import Navbar from "@/components/Navbar";

import Hero from "@/components/Hero";
import Catalog from "@/components/Catalog";
import Services from "@/components/Services";
import Footer from "@/components/Footer";
import {getAvailableProducts} from "@/firebase/products";
import {Product} from "@/app/type";


function Page() {
    const [products, setProducts] = React.useState<Product[]>([])

    useEffect(() => {
        async function fetchProducts() {
            const {result: data, error} = await getAvailableProducts();

            console.log({data, error})

            setProducts(data)
        }

        fetchProducts()

    }, [])
    return (
        <>
            <Head>
                <title>FoodStiks</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/app/favicon.ico"/>
            </Head>
            <main className='bg-yellow-200'>
                <div>
                    <Navbar/>
                    <Hero/>
                    <div className='bg-red-600'>
                        <h1 className='text-center text-5xl text-white p-8 uppercase font-bold '>Confira nosso
                            cardápio!</h1>
                        <div className='grid grid-cols-3 gap-5 '>
                            <Catalog products={products}/>
                        </div>
                    </div>
                </div>
                <Services/>
                <Footer/>
            </main>
        </>
    );
}

export default Page;
